<?php
/**
 * @file
 * directory_content_types.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function directory_content_types_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-places_to_eat-body'
  $field_instances['node-places_to_eat-body'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Eg. What’s the atmosphere/décor like? Are the waiting staff friendly? Is it a co-operative business?',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Description & additional comments',
    'required' => 0,
    'settings' => array(
      'display_summary' => 1,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 36,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_advandes_booking_necessary'
  $field_instances['node-places_to_eat-field_advandes_booking_necessary'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => 'Will people need to book in advance?',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 10,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_advandes_booking_necessary',
    'label' => 'Advanced booking necessary',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 0,
      ),
      'type' => 'options_onoff',
      'weight' => 24,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_amount_of_discount'
  $field_instances['node-places_to_eat-field_amount_of_discount'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'What percentage/amount of discount is this business offering to Viva! members?',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 26,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_amount_of_discount',
    'label' => 'Amount of discount',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 38,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_average_dessert_cost'
  $field_instances['node-places_to_eat-field_average_dessert_cost'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Average price for vegetarian/vegan dessert (Eg. £4.50).',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 31,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_average_dessert_cost',
    'label' => 'Average dessert cost',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 17,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_average_main_course_cost'
  $field_instances['node-places_to_eat-field_average_main_course_cost'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Average price for vegetarian/vegan main course (Eg. £4.50).',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 32,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_average_main_course_cost',
    'label' => 'Average main course cost',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 16,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_average_starter_cost'
  $field_instances['node-places_to_eat-field_average_starter_cost'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Average price for vegetarian/vegan starter (Eg. £4.50).',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 33,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_average_starter_cost',
    'label' => 'Average starter cost',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 15,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_clear_labelling'
  $field_instances['node-places_to_eat-field_clear_labelling'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => 'Vegan (or vegetarian) food is clearly labelled.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 11,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_clear_labelling',
    'label' => 'Vegan or vegetarian food is clearly labelled',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 0,
      ),
      'type' => 'options_onoff',
      'weight' => 13,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_cost_rating'
  $field_instances['node-places_to_eat-field_cost_rating'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 39,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_cost_rating',
    'label' => 'Cost rating',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 14,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_date_added'
  $field_instances['node-places_to_eat-field_date_added'] = array(
    'bundle' => 'places_to_eat',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'date',
        'settings' => array(
          'format_type' => 'long',
          'fromto' => 'both',
          'multiple_from' => '',
          'multiple_number' => '',
          'multiple_to' => '',
          'show_repeat_rule' => 'show',
        ),
        'type' => 'date_default',
        'weight' => 38,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_date_added',
    'label' => 'Date added',
    'required' => 0,
    'settings' => array(
      'default_value' => 'now',
      'default_value2' => 'same',
      'default_value_code' => '',
      'default_value_code2' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'date',
      'settings' => array(
        'display_all_day' => 0,
        'increment' => 15,
        'input_format' => 'm/d/Y - H:i:s',
        'input_format_custom' => '',
        'label_position' => 'above',
        'repeat_collapsed' => 0,
        'text_parts' => array(),
        'year_range' => '-3:+3',
      ),
      'type' => 'date_popup',
      'weight' => 41,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_discount_scheme_member'
  $field_instances['node-places_to_eat-field_discount_scheme_member'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => 'Is this business a member of our discount scheme?',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 25,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_discount_scheme_member',
    'label' => 'Discount scheme member',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 0,
      ),
      'type' => 'options_onoff',
      'weight' => 37,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_drinks_licensed_to_sell_al'
  $field_instances['node-places_to_eat-field_drinks_licensed_to_sell_al'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 12,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_drinks_licensed_to_sell_al',
    'label' => 'Drinks: Licensed to sell alcohol',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 0,
      ),
      'type' => 'options_onoff',
      'weight' => 21,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_drinks_offer_fair_trade_dr'
  $field_instances['node-places_to_eat-field_drinks_offer_fair_trade_dr'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 13,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_drinks_offer_fair_trade_dr',
    'label' => 'Drinks: Offer fair-trade drinks',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 0,
      ),
      'type' => 'options_onoff',
      'weight' => 19,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_drinks_offer_organic_drink'
  $field_instances['node-places_to_eat-field_drinks_offer_organic_drink'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 14,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_drinks_offer_organic_drink',
    'label' => 'Drinks: Offer organic drinks',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 0,
      ),
      'type' => 'options_onoff',
      'weight' => 20,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_drinks_vegan_wines_beers'
  $field_instances['node-places_to_eat-field_drinks_vegan_wines_beers'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 15,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_drinks_vegan_wines_beers',
    'label' => 'Drinks: Vegan wines/beers',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 0,
      ),
      'type' => 'options_onoff',
      'weight' => 22,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_drinks_vegetarian_wines_be'
  $field_instances['node-places_to_eat-field_drinks_vegetarian_wines_be'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 16,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_drinks_vegetarian_wines_be',
    'label' => 'Drinks: Vegetarian wines/beers',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 0,
      ),
      'type' => 'options_onoff',
      'weight' => 23,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_drinks_will_provide_soya_m'
  $field_instances['node-places_to_eat-field_drinks_will_provide_soya_m'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 17,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_drinks_will_provide_soya_m',
    'label' => 'Drinks: Will provide soya milk',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 0,
      ),
      'type' => 'options_onoff',
      'weight' => 18,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_facilities_disabled_facili'
  $field_instances['node-places_to_eat-field_facilities_disabled_facili'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => 'This business is accessible for people who use wheelchairs.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 18,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_facilities_disabled_facili',
    'label' => 'Facilities: Disabled facilities',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 0,
      ),
      'type' => 'options_onoff',
      'weight' => 25,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_facilities_dogs_allowed'
  $field_instances['node-places_to_eat-field_facilities_dogs_allowed'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 21,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_facilities_dogs_allowed',
    'label' => 'Facilities: Dogs allowed',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 0,
      ),
      'type' => 'options_onoff',
      'weight' => 27,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_facilities_parking'
  $field_instances['node-places_to_eat-field_facilities_parking'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 19,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_facilities_parking',
    'label' => 'Facilities: Parking',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 0,
      ),
      'type' => 'options_onoff',
      'weight' => 26,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_facilities_toilets'
  $field_instances['node-places_to_eat-field_facilities_toilets'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 20,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_facilities_toilets',
    'label' => 'Facilities: Toilets',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 0,
      ),
      'type' => 'options_onoff',
      'weight' => 28,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_image'
  $field_instances['node-places_to_eat-field_image'] = array(
    'bundle' => 'places_to_eat',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'image',
        'settings' => array(
          'image_link' => 'file',
          'image_style' => '2columns-140pixels',
        ),
        'type' => 'image',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_image',
    'label' => 'Image',
    'required' => 0,
    'settings' => array(
      'alt_field' => 0,
      'default_image' => 0,
      'file_directory' => '',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'max_resolution' => '',
      'min_resolution' => '',
      'title_field' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_location'
  $field_instances['node-places_to_eat-field_location'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Fill in the address details below, but leave the longitute and latitude blank (unless the point needs to be moved around mannually because the postcode has put it in slightly the wrong place, in which case just move the point around the map with your mouse).',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'location_cck',
        'settings' => array(),
        'type' => 'location_default',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_location',
    'label' => 'Location',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'location_cck',
      'settings' => array(),
      'type' => 'location',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_menu_example'
  $field_instances['node-places_to_eat-field_menu_example'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'What types of vegan/vegetarian dishes can people expect to order if they visit this business?',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 29,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_menu_example',
    'label' => 'Menu example',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 12,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_number_of_vegan_dishes_on_'
  $field_instances['node-places_to_eat-field_number_of_vegan_dishes_on_'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '(Eg. 5)',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 22,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_number_of_vegan_dishes_on_',
    'label' => 'Number of vegan dishes on the menu',
    'required' => 0,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 10,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_number_of_vegetarian_dishe'
  $field_instances['node-places_to_eat-field_number_of_vegetarian_dishe'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '(Eg. 5)',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 23,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_number_of_vegetarian_dishe',
    'label' => 'Number of vegetarian dishes on the menu',
    'required' => 0,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 11,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_opening_hours_friday'
  $field_instances['node-places_to_eat-field_opening_hours_friday'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 7,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_opening_hours_friday',
    'label' => 'Opening hours (Friday)',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 33,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_opening_hours_monday'
  $field_instances['node-places_to_eat-field_opening_hours_monday'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '<b>Examples:</b>
7pm - 11pm
11am - 3:30pm and 6pm - 8:45pm
CLOSED',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_opening_hours_monday',
    'label' => 'Opening hours (Monday)',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 29,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_opening_hours_saturday_'
  $field_instances['node-places_to_eat-field_opening_hours_saturday_'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '<b>Examples:</b>
7pm - 11pm
11am - 3:30pm and 6pm - 8:45pm
CLOSED',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 8,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_opening_hours_saturday_',
    'label' => 'Opening hours (Saturday)',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 34,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_opening_hours_sunday_'
  $field_instances['node-places_to_eat-field_opening_hours_sunday_'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '<b>Examples:</b>
7pm - 11pm
11am - 3:30pm and 6pm - 8:45pm
CLOSED',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 9,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_opening_hours_sunday_',
    'label' => 'Opening hours (Sunday)',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 35,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_opening_hours_thursday'
  $field_instances['node-places_to_eat-field_opening_hours_thursday'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '<b>Examples:</b>
7pm - 11pm
11am - 3:30pm and 6pm - 8:45pm
CLOSED',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 6,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_opening_hours_thursday',
    'label' => 'Opening hours (Thursday)',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 32,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_opening_hours_tuesday'
  $field_instances['node-places_to_eat-field_opening_hours_tuesday'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '<b>Examples:</b>
7pm - 11pm
11am - 3:30pm and 6pm - 8:45pm
CLOSED',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_opening_hours_tuesday',
    'label' => 'Opening hours (Tuesday)',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 30,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_opening_house_wednesday'
  $field_instances['node-places_to_eat-field_opening_house_wednesday'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '<b>Examples:</b>
7pm - 11pm
11am - 3:30pm and 6pm - 8:45pm
CLOSED',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 5,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_opening_house_wednesday',
    'label' => 'Opening house (Wednesday)',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 31,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_percentage_of_vegan_food'
  $field_instances['node-places_to_eat-field_percentage_of_vegan_food'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Percentage of vegan food on the menu (eg. 10%)',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 34,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_percentage_of_vegan_food',
    'label' => 'Percentage of vegan food',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 8,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_percentage_of_vegetarian_f'
  $field_instances['node-places_to_eat-field_percentage_of_vegetarian_f'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Roughly what percentage of the food is vegetarian (eg. 40%)?',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 35,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_percentage_of_vegetarian_f',
    'label' => 'Percentage of vegetarian food',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 9,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_product_section'
  $field_instances['node-places_to_eat-field_product_section'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_link',
        'weight' => 40,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_product_section',
    'label' => 'Product section',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_symbol_holder'
  $field_instances['node-places_to_eat-field_symbol_holder'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 27,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_symbol_holder',
    'label' => 'Symbol holder',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 0,
      ),
      'type' => 'options_onoff',
      'weight' => 39,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_type_of_business'
  $field_instances['node-places_to_eat-field_type_of_business'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 24,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_type_of_business',
    'label' => 'Type of business',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_type_of_food_served'
  $field_instances['node-places_to_eat-field_type_of_food_served'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Indian, Italian, Mexican, Thai etc.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 36,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_type_of_food_served',
    'label' => 'Type of food served',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 7,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_type_of_symbol'
  $field_instances['node-places_to_eat-field_type_of_symbol'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 28,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_type_of_symbol',
    'label' => 'Type of symbol',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 40,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_vegn_options'
  $field_instances['node-places_to_eat-field_vegn_options'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => array(
      0 => array(
        'tid' => 24,
      ),
    ),
    'deleted' => 0,
    'description' => '<b>Vegan:</b> All food and drinks are vegan.
<b>Vegan friendly:</b> Allthough not all food/drinks are vegan, they are good at catering for vegans.
<b>Vegetarian:</b> All food and drinks are vegetarian.
<b>Vegetarian friendly:</b> Allthough not all food/drinks are Vegetarian, they are good at catering for Vegetarians.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_link',
        'weight' => 30,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_vegn_options',
    'label' => 'Vegn options',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 6,
    ),
  );

  // Exported field_instance: 'node-places_to_eat-field_website_address'
  $field_instances['node-places_to_eat-field_website_address'] = array(
    'bundle' => 'places_to_eat',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Eg. www.google.com',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'link',
        'settings' => array(),
        'type' => 'link_default',
        'weight' => 37,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_website_address',
    'label' => 'Website address',
    'required' => 0,
    'settings' => array(
      'absolute_url' => 1,
      'attributes' => array(
        'class' => '',
        'configurable_title' => 0,
        'rel' => '',
        'target' => '_blank',
        'title' => '',
      ),
      'display' => array(
        'url_cutoff' => 80,
      ),
      'enable_tokens' => 1,
      'title' => 'none',
      'title_label_use_field_label' => FALSE,
      'title_maxlength' => 128,
      'title_value' => '',
      'url' => 0,
      'user_register_form' => FALSE,
      'validate_url' => 1,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'link',
      'settings' => array(),
      'type' => 'link_field',
      'weight' => 4,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('(Eg. 5)');
  t('<b>Examples:</b>
7pm - 11pm
11am - 3:30pm and 6pm - 8:45pm
CLOSED');
  t('<b>Vegan:</b> All food and drinks are vegan.
<b>Vegan friendly:</b> Allthough not all food/drinks are vegan, they are good at catering for vegans.
<b>Vegetarian:</b> All food and drinks are vegetarian.
<b>Vegetarian friendly:</b> Allthough not all food/drinks are Vegetarian, they are good at catering for Vegetarians.');
  t('Advanced booking necessary');
  t('Amount of discount');
  t('Average dessert cost');
  t('Average main course cost');
  t('Average price for vegetarian/vegan dessert (Eg. £4.50).');
  t('Average price for vegetarian/vegan main course (Eg. £4.50).');
  t('Average price for vegetarian/vegan starter (Eg. £4.50).');
  t('Average starter cost');
  t('Cost rating');
  t('Date added');
  t('Description & additional comments');
  t('Discount scheme member');
  t('Drinks: Licensed to sell alcohol');
  t('Drinks: Offer fair-trade drinks');
  t('Drinks: Offer organic drinks');
  t('Drinks: Vegan wines/beers');
  t('Drinks: Vegetarian wines/beers');
  t('Drinks: Will provide soya milk');
  t('Eg. What’s the atmosphere/décor like? Are the waiting staff friendly? Is it a co-operative business?');
  t('Eg. www.google.com');
  t('Facilities: Disabled facilities');
  t('Facilities: Dogs allowed');
  t('Facilities: Parking');
  t('Facilities: Toilets');
  t('Fill in the address details below, but leave the longitute and latitude blank (unless the point needs to be moved around mannually because the postcode has put it in slightly the wrong place, in which case just move the point around the map with your mouse).');
  t('Image');
  t('Indian, Italian, Mexican, Thai etc.');
  t('Is this business a member of our discount scheme?');
  t('Location');
  t('Menu example');
  t('Number of vegan dishes on the menu');
  t('Number of vegetarian dishes on the menu');
  t('Opening hours (Friday)');
  t('Opening hours (Monday)');
  t('Opening hours (Saturday)');
  t('Opening hours (Sunday)');
  t('Opening hours (Thursday)');
  t('Opening hours (Tuesday)');
  t('Opening house (Wednesday)');
  t('Percentage of vegan food');
  t('Percentage of vegan food on the menu (eg. 10%)');
  t('Percentage of vegetarian food');
  t('Product section');
  t('Roughly what percentage of the food is vegetarian (eg. 40%)?');
  t('Symbol holder');
  t('This business is accessible for people who use wheelchairs.');
  t('Type of business');
  t('Type of food served');
  t('Type of symbol');
  t('Vegan (or vegetarian) food is clearly labelled.');
  t('Vegan or vegetarian food is clearly labelled');
  t('Vegn options');
  t('Website address');
  t('What percentage/amount of discount is this business offering to Viva! members?');
  t('What types of vegan/vegetarian dishes can people expect to order if they visit this business?');
  t('Will people need to book in advance?');

  return $field_instances;
}
